### PR TITLE
Enhancement/more

### PR DESCRIPTION
**Pull request by jlp765**
Benchmarking additions
exit from MAIN fix to run END before exit
fix FNR bug to keep its value after MAIN
fix getline result in BEGIN
Update and enable PROCINFO and add FUNCTAB
fix sorting error for sorttype 4
add ability to sort values, not just keys
add typeof()
add isarray()
Fix length() to handle arrays for Gawk compatibility
add RE syntax style selecting and make default more compatible with Gawk
add Python benchmarks
et. al.

### CODE REVIEW

**Comment by noyesno** [comment]
Some test failed. Need further debugging.

**Comment by jlp765** [comment]
Using RE_SYNTAX_POSIX_AWK for the eiso2 test which is very recursive causes a memory allocation error I think.
Using the simpler syntaxes doesn't hit this problem.  Quite a rabbit hole to get to the bottom of this one :-)

**Review by noyesno — APPROVED** [review]
if user want to keep FNR, it's better to explicitly save it in block ENDFILE.
Using FNR in END block is not the suggested way.

**Review by noyesno — COMMENTED** [review]
## Testcase

`echo abc | awk '{ exit } END {print "END"}'`

## man gawk

> Similarly, all the END blocks are merged, and executed when all the input is exhausted (or when an exit statement is executed)

**Pull request merged**
